Repository BitCamp-Final-Project/Dr.Rate-Frontend, pull requests merged in 2024-12, with the labels that each got.

#92 캘린더 반응형, 로고 출력
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client, feat

#97 Fix/product detail page
  src/App.jsx
  src/pages/ProductDetailPage/ProductDetailPage.jsx
Labels: fix

#99 Feat/product compare page
  src/App.jsx
  src/apis/productsAPI.js
  src/components/Header/Header.jsx
  src/components/Modal/CompareModal/CompareModal.jsx
  src/components/Modal/CompareModal/CompareModal.module.scss
  src/components/Modal/CompareModal/index.js
  src/hooks/useCheckedBanks.js
  src/hooks/useCompare.js
  src/hooks/useProducts.js
  src/pages/ProductComparePage/ProductComparePage.jsx
  src/pages/ProductComparePage/ProductComparePage.module.scss
  src/pages/ProductComparePage/index.js
  src/pages/ProductDetailPage/ProductDetailPage.jsx
  src/pages/ProductDetailPage/ProductDetailPage.module.scss
  src/pages/ProductDetailPage/RateCalc/RateCalc.jsx
  src/pages/index.js
  src/styles/color.css
  src/utils/path.js
Labels: feat

#106 feat : 예금상품 DB연동 테스트 완료, SCSS & JSX 보완 완료 / 오혜진
  src/pages/ProductDepListPage/ProductDepListPage.jsx
  src/pages/ProductDepListPage/ProductDepListPage.module.scss
Labels: client

#197 Fix/product detail page
  src/apis/productsAPI.js
  src/hooks/useCalc.js
  src/hooks/useProducts.js
  src/pages/ProductDetailPage/ProductDetailPage.jsx
  src/pages/ProductDetailPage/ProductDetailPage.module.scss
  src/pages/ProductDetailPage/RateCalc/RateCalc.jsx
  src/pages/ProductDetailPage/RateCalc/RateCalc.module.scss
Labels: fix

#199 Feat/product compare page
  src/apis/productsAPI.js
  src/components/Header/Header.jsx
  src/components/Modal/CompareModal/CompareModal.jsx
  src/components/Modal/CompareModal/CompareModal.module.scss
  src/hooks/useCalc.js
  src/hooks/useCheckedBanks.js
  src/hooks/useDragScroll.js
  src/pages/ProductComparePage/ProductComparePage.jsx
  src/pages/ProductComparePage/ProductComparePage.module.scss
  src/pages/ProductDetailPage/ProductDetailPage.jsx
Labels: feat

#204 Fix/product detail page
  src/components/CompareNav/CompareNav.jsx
  src/components/CompareNav/CompareNav.module.scss
  src/components/CompareNav/index.js
  src/pages/ProductDetailPage/ProductDetailPage.jsx
  src/pages/ProductDetailPage/ProductDetailPage.module.scss
Labels: fix

#208 feat: 비교추가 반응형 수정
  src/components/CompareNav/CompareNav.modale.scss
  src/components/Modal/CompareModal/CompareModal.jsx
  src/components/Modal/CompareModal/CompareModal.module.scss
Labels: feat

#217 fix: footer 반응형 추가
  src/components/CompareNav/CompareNav.jsx
  src/components/CompareNav/CompareNav.modale.scss
  src/components/CompareNav/CompareNav.module.scss
  src/components/Footer/Footer.module.scss
Labels: fix, client

#234 Fix/chat UI update
  src/hooks/useCalc.js
  src/pages/My1v1InquirePage/My1v1InquirePage.jsx
  src/pages/My1v1InquirePage/My1v1InquirePage.module.scss
Labels: fix, client

#256 fix: 상품 비교담기 기능 추가, 오류 수정
  src/hooks/useProducts.js
  src/pages/ListDepositPage/ListDepositPage.jsx
  src/pages/ListInstallmentPage/ListInstallmentPage.jsx
  src/pages/ProductDetailPage/ProductDetailPage.jsx
Labels: fix, client
