Repository BitCamp-Final-Project/Dr.Rate-Frontend, pull requests merged in 2024-11, with the labels that each got.

#5 fix: 메인페이지 가운데 정렬 해결
  src/assets/images/homePageBG.png
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
Labels: bug, client

#16 conf: package.json, yarn.lock 라이브러리 설치로 인한 업데이트
  package.json
  yarn.lock
Labels: client

#21 Feat/footer
  src/assets/icons/appstoreIcon.svg
  src/assets/icons/faviconIcon.svg
  src/assets/icons/footerDivider.svg
  src/assets/icons/labIcon.svg
  src/assets/icons/playstoreIcon.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/index.js
  src/components/Header/index.js
Labels: client

#25 Feat/mynav 서뷰 메뉴 작업 중
  src/components/MyNav/MyNav.jsx
  src/components/MyNav/MyNav.module.scss
Labels: client

#26 Feat/modal
  public/logo192.png
  public/logo512.png
  src/styles/color.css
Labels: client

#27 conf: 검색 아이콘, 정보 아이콘 추가
  src/assets/icons/infoIcon.svg
  src/assets/icons/searchIcon.svg
Labels: client

#29 Feat/product detail page
  src/App.jsx
  src/components/Header/Header.jsx
  src/components/RateCalc/RateCalc.jsx
  src/components/RateCalc/RateCalc.module.scss
  src/components/RateCalc/index.js
  src/pages/ProductDetailPage/ProductDetailPage.jsx
  src/pages/ProductDetailPage/ProductDetailPage.module.scss
  src/pages/ProductDetailPage/index.js
  src/pages/index.js
  src/utils/path.js
Labels: client

#31 Feat/calendar 수정완료
  src/assets/bank/hanaLogo.png
  src/assets/bank/kakaoLogo.png
  src/assets/bank/kookminLogo.png
  src/assets/bank/nonghyupLogo.png
  src/assets/bank/remainLogo.png
  src/assets/bank/shinhanLogo.png
  src/assets/bank/tossLogo.png
  src/assets/bank/wooriLogo.png
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client

#33 Feat/header my nav
  src/App.jsx
  src/assets/icons/downDetailArrow.svg
  src/assets/icons/downWideArrow.svg
  src/assets/images/adminDashboard.png
  src/assets/images/adminInquiryHistory.png
  src/assets/images/adminLogo.png
  src/assets/images/adminUserManagement.png
  src/components/AdminSideNav/AdminSideNav.jsx
  src/components/AdminSideNav/AdminSideNav.module.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/pages/AdminMainPage/AdminMainPage.jsx
  src/pages/MyDepositPage/MyDepositPage.jsx
  src/pages/MyDepositPage/MyDepositPage.module.scss
  src/pages/MyDepositPage/index.js
  src/pages/MyInstallmentPage/MyInstallmentPage.jsx
  src/pages/MyInstallmentPage/MyInstallmentPage.module.scss
  src/pages/MyInstallmentPage/index.js
  src/pages/MyRecurringPage/MyRecurringPage.jsx
  src/pages/MyRecurringPage/index.js
  src/pages/MySavingsPage/index.js
  src/pages/ProductDetailPage/ProductDetailPage.jsx
  src/pages/index.js
  src/styles/color.css
  src/utils/path.js
Labels: client

#35 Feat/calendar 마이페이지 경로수정
  src/assets/icons/leftArrow.svg
  src/assets/icons/rightArrow.svg
  src/components/Header/Header.jsx
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client

#38 Feat/Header-MyNav
  package.json
  src/App.jsx
  src/assets/icons/upWideArrow.svg
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/index.js
  src/components/MyNav/MyNav.jsx
  src/components/MyNav/MyNav.module.scss
  src/components/MyNav/index.js
  src/hooks/useDropdown.js
  src/pages/MyDepositPage/MyDepositPage.jsx
  src/pages/MyDepositPage/MyDepositPage.module.scss
  src/pages/ProductDetailPage/index.js
  src/pages/index.js
  src/utils/path.js
  yarn.lock
Labels: client

#37 feat : 관리자 헤더 & 대시보드 & 사용자 조회 UI 구현 완료
  README.md
  package.json
  src/App.jsx
  src/assets/icons/userIcon.png
  src/components/AdminHeader/AdminHeader.module.scss
  src/components/AdminSideNav/AdminSideNav.jsx
  src/components/AdminSideNav/AdminSideNav.module.scss
  src/pages/AdminInquireListPage/AdminInquireListPage.jsx
  src/pages/AdminInquireListPage/AdminInquireListPage.module.scss
  src/pages/AdminInquireListPage/index.js
  src/pages/AdminInquirePage/AdminInquirePage.module.scss
  src/pages/AdminMainPage/AdminMainPage.jsx
  src/pages/AdminMainPage/AdminMainPage.module.scss
  src/pages/AdminUserListPage/AdminUserListPage.jsx
  src/pages/AdminUserListPage/AdminUserListPage.module.scss
  src/pages/AdminUserListPage/index.js
  src/pages/index.js
  src/styles/color.css
  src/utils/path.js
  yarn.lock
Labels: client

#42 Feat/modal
  src/atoms/alertAtom.js
  src/components/Modal/AlertModal/AlertModal.jsx
  src/components/Modal/AlertModal/AlertModal.module.scss
  src/components/Modal/AlertModal/Test01.jsx
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client, feat

#43 feat : hooks로 수정
  src/atoms/alertAtom.js
  src/components/Modal/AlertModal/AlertModal.jsx
  src/components/Modal/AlertModal/AlertModal.module.scss
  src/hooks/useModal.js
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client, feat

#45 feat : confirm 추가 및 calendar수정
  src/components/Modal/AlertModal/AlertModal.module.scss
  src/components/Modal/ConfirmModal/ConfirmModal.jsx
  src/components/Modal/ConfirmModal/ConfirmModal.module.scss
  src/hooks/useModal.js
  src/pages/MyCalendarPage/MyCalendarPage.jsx
  src/pages/MyCalendarPage/MyCalendarPage.module.scss
Labels: client, feat

#50 Feat/product ins list page
  package.json
  src/App.jsx
  src/pages/ProductInsListPage/ProductInsListPage.jsx
  src/pages/ProductInsListPage/ProductInsListPage.module.scss
  src/pages/ProductInsListPage/index.js
  src/pages/index.js
  src/utils/path.js
  yarn.lock
Labels: client

#51 Feat/responsive
  src/App.jsx
  src/assets/icons/mobileMenuIcon.svg
  src/assets/icons/mobileSideCompare.png
  src/assets/icons/mobileSideDeposit.png
  src/assets/icons/mobileSideInstallment.png
  src/assets/icons/mobileSideProfile.svg
  src/components/AdminSideNav/AdminSideNav.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/MyNav/MyNav.jsx
  src/index.css
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/styles/color.css
  src/styles/init.css
  src/utils/path.js
Labels: client
